media: images
content:
  - name: config
    label: Quarto config
    path: _quarto.yml
    type: file
    fields:
      - name: website
        type: object
        fields:
          - name: navbar
            type: object
            fields:
              - { name: background, label: Background color, type: string}
  - name: about
    label: About
    type: file
    path: index.qmd
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: subtitle, label: Subtitle, type: string, required: true }
      - name: about
        label: About page config
        type: object
        fields:
          - name: template
            label: Template
            type: select
            options:
              values: [ jolla, trestles, solana, marquee, broadside]
          - { name: image, label: Image, type: image}
      - { name: body, label: Body, type: rich-text }
  - name: projects
    label: Projects
    path: topics
    type: collection
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: image, label: Image, type: image}
      - { name: body, label: Body, type: rich-text }
    filename: "{primary}.md"
  - name: pages
    label: Pages
    path: topics
    type: collection
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: image, label: Image, type: image}
      - { name: body, label: Body, type: rich-text }
    filename: "{primary}.md"