project:
  type: website
website:
  title: sceds4youth
  navbar:
    background: "#ede3ee"
    left:
      - text: About
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Collaborations
        href: pages/collaborations.qmd
      - text: Dissemination
        href: pages/dissemination.qmd
      - text: News
        href: pages/news.qmd
      - text: Contact
        href: pages/contact.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
