project:
  type: website
website:
  title: asdf
  navbar:
    background: "#2596be"
    left:
      - text: About
        href: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
