---
title: Research and Training Center
subtitle: For studying within-person treatment effects using Single-Case
  Experimental Designs
about:
  template: trestles
---
About us

We are a team of researchers and scientist-practicioners passionate about improving the science and practice of treatments for youth psychopathology. While tremendous amount of progress has been made with regard to the knowledge on the efficacy and effectiveness of youth treatments in the past decades, some questions still remain unresolved: Why don’t some youths improve after treatment? Hoe can we individually tailor treatments for youths and investigate effects? What are the working mechanisms (mediators) responsible for the effects? How can we personalize, and how can we really bridge the gap between science and practice, and create more evidence-based youth clinical practice? To answer these and similar questions we implement single-case experimental design methods, and we train scientist-practicioners in becoming capable to do so as well. Take a look at our webpage.

_We are thankful to Max Paulus from the UvA Research Lab and dog Lucky for helping us create these pages!_ 

_Dutch version of the website follows soon._

**Marija Maric, Ph.D.,** is an Associate Professor at the University of Amsterdam, department of Child Development and Education. After finishing MA in Clinical Psychology at Leiden University, she conducted a PhD program during which she investigated mediators and moderators of treatment outcomes for internalizing disorders and school refusal in children, adolescents, and their families. Hereafter she moved to the University of Amsterdam and developed a research line involving using single-case experimental design methods to study effectiveness, mediators and moderators of youth interventions. Marija received her cognitive behavioral therapist’s degree in 2017. She has over 20 years of teaching and supervising experience in bachelor, (research) master and postgraduate education. Leadership/management.